spring:
  datasource:
    url: jdbc:mysql://localhost:3306/um_db    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  batch:    initialize-schema: ALWAYS
    job:      enabled: false  thymeleaf:    cache: false    enabled: true